API/urls.py
from django.urls import include, path
from rest_framework import routers
from .views import MyModelViewSet

router = routers.DefaultRouter()
router.register(r'mymodels', MyModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

Ecommerce_Template/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user/', include('core.urls')),
    path('payments/', include('payments.urls')),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    # PaymentView,
    # AddCouponView,
    # RequestRefundView,
    login_view,
    register_view,
    cart_view,
    profile_view,
    logout_view,
    add_address_view,
    remove_address_view,
    edit_address_view
)

app_name = 'core'

urlpatterns = [
    # path('checkout/', CheckoutView.as_view(), name='checkout'),
    #path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    # path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    # path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('login', login_view, name="login"),
    path('register', register_view, name="register"),
    path('cart', cart_view, name='cart'),
    path('profile', profile_view, name="profile"),
    path('add-address', add_address_view, name="address"),
    path('logout', logout_view, name='logout'),
    path('remove-address/<str:title>/', remove_address_view, name='remove-address'),
    path('edit-address/<str:title>/', edit_address_view, name='edit-address'),
]

payments/urls.py
from django.urls import path
from .views import *

app_name = 'payments'

urlpatterns = [
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('process-payment/', process_payment, name='process_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
]

store/urls.py
from django.urls import path
from .views import *

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<slug>', ProductDetails.as_view(), name='product_view'),
    path('products', ProductView.as_view(), name='products'),
    path('search', product_search, name='search')
]

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.

templates/Test_site/index.html
{% extends "base.html" %} {% load static %}

{% block title %} Hardware Store {% endblock %}
{% block hero %}

<div class="hero__item set-bg" data-setbg="{% static 'img/main_page/banner.jpg' %}">
    <div class="hero__text">
        <span>TOP QUALITY</span>
        <h2>Your <br />Products</h2>
        <p>Free Pickup and Delivery Available</p>
        <a href="#" class="primary-btn">SHOP NOW</a>
    </div>
</div>
{% endblock %}
{% block content %}

<!-- Hero Section End -->

<!-- Categories Section Begin -->
<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel">
                {% for category in Featured %}
                <div class="col-lg-3">
                    <div class="categories__item set-bg" data-setbg="{{ MEDIA_URL }}{{ category.image.url }}">
                        <h5><a href="#">{{ category.title }}</a></h5>
                    </div>
                </div>
                {% endfor %}
                
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->

<!-- Featured Section Begin -->
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
                <div class="featured__controls">
                    <ul>
                        <li class="active" data-filter="*">All</li>
                        {% for category in Categories %}
                            <li data-filter=".oranges">{{category.abbreviation}}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            {% for product in Products %}
            <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="{{ MEDIA_URL }}{{ product.image.url }}">
                        <ul class="featured__item__pic__hover">
                            <li><a href="#"><i class="fa fa-heart"></i></a></li>
                            <li><a href="{% url 'store:product_view' product.slug %}"><i class="fa fa-retweet"></i></a></li>
                            <li><a href="{% url 'core:add-to-cart' slug=product.slug %}"><i class="fa fa-shopping-cart"></i></a></li>
                        </ul>
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="#">{{ product.title }}</a></h6>
                        <h5>${{ product.price }}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Featured Section End -->

<!-- Banner Begin -->
<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="{% static 'img/main_page/banner-2.png' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="banner__pic">
                    <img src="{% static 'img/main_page/banner-1.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner End -->

<!-- Latest Product Section Begin -->
<section class="latest-product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Latest Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                            {% for product in Latest1 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                            {% for product in Latest2 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Top Rated Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                            {% for product in Rating1 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                            {% for product in Rating2 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="latest-product__text">
                    <h4>Review Products</h4>
                    <div class="latest-product__slider owl-carousel">
                        <div class="latest-prdouct__slider__item">
                            {% for product in Rating1 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                        <div class="latest-prdouct__slider__item">
                            {% for product in Rating2 %}
                            <a href="#" class="latest-product__item">
                                <div class="latest-product__item__pic">
                                    <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="">
                                </div>
                                <div class="latest-product__item__text">
                                    <h6>{{product.title}}</h6>
                                    <span>${{product.price}}</span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Latest Product Section End -->

<!-- Blog Section Begin -->
<section class="from-blog spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title from-blog__title">
                    <h2>From The Blog</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="img/blog/blog-1.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Cooking tips make cooking simple</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="img/blog/blog-2.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">6 ways to prepare breakfast for 30</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="blog__item">
                    <div class="blog__item__pic">
                        <img src="img/blog/blog-3.jpg" alt="">
                    </div>
                    <div class="blog__item__text">
                        <ul>
                            <li><i class="fa fa-calendar-o"></i> May 4,2019</li>
                            <li><i class="fa fa-comment-o"></i> 5</li>
                        </ul>
                        <h5><a href="#">Visit the clean farm in the US</a></h5>
                        <p>Sed quia non numquam modi tempora indunt ut labore et dolore magnam aliquam quaerat </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    <!-- Blog Section End -->
{% endblock %}

templates/Test_site/login.html
{% load static %}
{% load socialaccount %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'Test_site/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/login-style.css' %}" type="text/css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
</head>

<body>
    <div id="login-form-wrap">
      <img id="logo" src="{% static 'img/sample-logo.png' %}" alt="">
        <h2>Login</h2>
        <form id="login-form" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <p>
          <input type="text" id="username" name="username" placeholder="Username" required><i class="validation"><span></span><span></span></i>
          </p>
          <p>
            <input type="password" id="password" name="password" placeholder="Password" required><i class="validation"><span></span><span></span></i>
          </p>
          <h3>Or</h3>
          <p>
            <ul>
              <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
              <li><a href="{% provider_login_url 'google' %}"><i class="fa fa-google" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
              <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            </ul>
          </p>
          <p>
          <input type="submit" id="login" value="Login">
          </p>  
        </form>
        <div id="create-account-wrap">
          <p>Not a member? <a href="{% url 'core:register' %}">Create Account</a><p>
          <p>Forgot password? <a href="#"> Click here.</a><p></p>
        </div><!--create-account-wrap-->
      </div><!--login-form-wrap-->
</body>

</html>

templates/Test_site/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/Test_site/profile.html
{% extends "base.html" %} {% load static %}

{% block title %} Hardware Store {% endblock %}

{% block style %}
<style>
    .hero{
        padding-bottom: 0px;
    }
    .hero__categories ul {
        position: absolute;
        left: 0;
        top: 46px;
        width: calc(100% - 30px);
        z-index: 9;
        background: #343a40;
        margin-left: 15px;
        border: 1px solid #252525;
    }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5" style="background-color: #212529;">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column p-3 py-5">
                <span class="profile-title font-weight-bold">{{ user.username }} </span>
                <span class="text-white-50">{{user.email}}</span>
                <span class="text-white-50">{{user.address_info.country}}</span>
                <span> </span>
                <h4 class="text-white-50">Payment methods</h4>

                <div class="d-flex justify-content-between align-items-center experience">
                    {% for address in addresses %}
                    <p> {{address.title}} </p>
                    {% endfor %}
                </div><br>

                <a class="primary-btn" href="{% url 'core:logout'%}">Log out</a>
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="profile-title text-right">Profile Settings</h4>
                </div>

                {% for address in user.addresses.all %}
                <div class="Address-box">
                    <div class="Address-title">
                        <h5> {{address.title}} </h5> <h5> {{address.country}} </h5>
                    </div>
                    <p> {{ address.address_long}}</p>
                    <p> Floor: {{address.apartment_floor}} - Flat: {{address.apartment_flat}}</p>
                    <p> Zip: {{address.zip}} - Type: {{address.address_type}} </p>
                    <div class="Address-title">
                        <a href="{% url 'core:edit-address' title=address.title%}"><i class='fa fa-edit' style="color: white;"></i></a>
                        <a href="{% url 'core:remove-address' title=address.title%}"><i class='fa fa-trash' style="color: white;"></i></a>
                    </div>
                </div>
                {% endfor %}
                
                <div class="mt-5 text-center"><a href="{% url 'core:address' %}" class="primary-btn">New address</a></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <span class="profile-title">Past orders</span>
                <div class="d-flex justify-content-between align-items-center experience">
                    {% for order in Orders %}
                    <div class="order-display">
                        <h1>{{ order.shipping_address.title }}</h1>
                    </div>
                    {% endfor %}
                </div><br>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/Test_site/register.html
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'Test_site/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'Test_site/css/login-style.css' %}" type="text/css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
</head>

<body>
    <div id="login-form-wrap">
      <img id="logo" src="{% static 'img/sample-logo.png' %}" alt="">
                    
        <h2>Register</h2>
        <form id="login-form" method="POST" action="{% url 'core:register' %}">
          {% csrf_token %}
          <p>
          <input type="text" id="username" name="username" placeholder="Username" required><i class="validation"><span></span><span></span></i>
          </p>
          <p>
          <input type="email" id="email" name="email" placeholder="Email Address" required><i class="validation"><span></span><span></span></i>
          </p>
          <p>
            <input type="password" id="password1" name="password1" placeholder="Password" required><i class="validation"><span></span><span></span></i>
          </p>
          <p>
            <input type="password" id="password2" name="password2" placeholder="Password again" required><i class="validation"><span></span><span></span></i>
          </p>
          <p>
          <input type="submit" id="login" value="Register">
          </p>
        </form>
        <div id="create-account-wrap">
          <p>
            Your personal data is not being proccessed other then delivery purposes.
            You can read more in our terms and services page.
          </p>
        </div><!--create-account-wrap-->
      </div><!--login-form-wrap-->
</body>

</html>

templates/Test_site/shoping-cart.html
{% extends "base.html" %} {% load static %}

{% block title %} Cart {% endblock %}

{% block style %}
<style>
    .hero{
        padding-bottom: 0px;
    }
    .hero__categories ul {
        position: absolute;
        left: 0;
        top: 46px;
        width: calc(100% - 30px);
        z-index: 9;
        background: #343a40;
        margin-left: 15px;
        border: 1px solid #252525;
    }
</style>
{% endblock %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'img/main_page/cart.png' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in CartItems %}
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img src="{{ MEDIA_URL }}{{ cart_item.item.image.url }}" alt="">
                                        <h5>{{ cart_item.item.title }}</h5>
                                    </td>
                                    <td class="shoping__cart__price">
                                        ${{cart_item.item.price}}
                                    </td>
                                    <td class="shoping__cart__quantity">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                                <input type="text" value="{{cart_item.quantity}}">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="shoping__cart__total">
                                        ${{cart_item.get_total_item_price}}
                                    </td>
                                    <td class="shoping__cart__item__close">
                                        <a href="{% url 'core:remove-from-cart' slug=cart_item.item.slug %}">
                                            <img src="{% static 'img/icons/trash-icon.png' %}">
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__btns">
                        <a href="#" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                        <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                            Upadate Cart</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__continue">
                        <div class="shoping__discount">
                            <h5>Discount Codes</h5>
                            <form action="#">
                                <input type="text" placeholder="Enter your coupon code">
                                <button type="submit" class="site-btn">APPLY COUPON</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Subtotal <span>${{Subtotal}}</span></li>
                            <li>Tax <span>%{{Tax}}</span></li>
                            <li>Total <span>${{Total}}</span></li>
                        </ul>
                        <a href="{% url 'payments:checkout' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->
    {% endblock %}